# Generated by Django 5.1.5 on 2025-02-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembermodules',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='teammembermodules',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='teammembermodules',
            old_name='team_Id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='teammembers',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='teammembers',
            old_name='team_Id',
            new_name='team',
        ),
    ]
