# Generated by Django 5.1.5 on 2025-02-01 09:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_member_id_teammembermodules_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
        migrations.RenameModel(
            old_name='TeamMemberModules',
            new_name='TeamMemberModule',
        ),
    ]
